variables:
    DEBFULLNAME: "GitLab CI"
    DEBEMAIL: "gitlabci@localhost"
    VERSION_TO_BUILD: "4.3.2"

stages:
    - lint
    - build

image: debian:stretch

lint:scripts:
    stage: lint
    tags:
        - docker
    before_script:
        - apt-get update && apt-get install -y shellcheck
    script:
        - shellcheck build.sh

build:sogo:
    stage: build
    tags:
        - docker
    script:
        - ./build.sh
    artifacts:
        expire_in: 1 week
        when: always
        paths:
            - vendor/*.deb
